# Generated by Django 2.2.17 on 2020-11-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('price', models.FloatField()),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
